---
# vim: bs=2 sw=2 expandtab:
#
# the one-liner should append the lvm_disk variable to this file like the
# following example:
#
# lvm_disk:
#   device: '/dev/sdb'
#   lvm_vg: 'vg_rgmdata'
#   partitions:
#   - name: 'rgm'
#     mountpoint: '/srv/rgm'
#     filesystem: 'ext4'
#     size: '20G'

# RGM base path
rgm_root_path: /srv/rgm

# RGM snmp community name
snmp_ro_community: RGM

# install extra plugins for grafana - uncomment if you wish to change the default behavior
# grafana_install_plugins_core: True
# grafana_install_plugins_contrib: False

mkdocs_source_dir: "{{ ansible_env.PWD }}/mkdocs"
mkdocs_root_dir: "{{ rgm_root_path }}/mkdocs"
