---

# the one-liner should append the lvm_disk variable to this file like the
# following example:
#
# lvm_disk:
#   device: '/dev/sdb'
#   lvm_vg: 'vg_rgmdata'
#   partitions:
#   - name: 'rgm'
#     mountpoint: '/srv/rgm'
#     filesystem: 'ext4'
#     size: '20G'

# install extra plugins for grafana
grafana_install_plugins: False
