---

- name: "Pre-flight play for host conformance"
  hosts: rgm
  remote_user: root

  tasks:
    - name: "Ensure host_vars is linked to /etc/rgm"
      ansible.builtin.file:
        path: host_vars/localhost
        state: link

    - name: "Ensure obsolete RPM repos are removed"
      loop:
        - rgm-community
        - rgm-partners
      ansible.builtin.file:
        path: "/etc/yum.repos.d/{{ item }}.repo"
        state: absent



- name: "RGM install play"
  hosts: rgm
  remote_user: root
  roles:
    - { role: role-lvm-partitionner }
    - { role: role-snmp }
    - { role: role-rgm }
