---
- name: "Configure RGM and Elasticsearch node for ES RGM cluster"
  hosts: elastic
  remote_user: root

  vars:
    # When upgrading a single ES node to cluster mode, it storage backend
    # must be deleted.
    #force_delete_es: true

  tasks:
    - name: "Test"
      ansible.builtin.include_role:
        name: ansible-role-rgm
        tasks_from: elastic/elastic_cluster.yml
